export const MUDRAS = [
  {
    id: '1',
    slug: 'pataka',
    name: 'Pataka',
    category: 'Asamyukta Hasta',
    meaning: 'Flag',
    difficulty: 'Beginner',
    meaningLong: 'The Pataka gesture is the most basic single-hand gesture in Bharatanatyam. It represents a flag, clouds, forest, or river.',
    significance: 'It is used to represent a vast range of objects and actions, including opening a door, a forest, or a king.',
    instructions: 'Keep all fingers straight and close together. Bend the thumb slightly to touch the side of the palm.',
    commonMistakes: 'Spacing between fingers or bending the fingertips.',
    image: '/images/mudras/pataka.jpg',
  },
  {
    id: '2',
    slug: 'tripataka',
    name: 'Tripataka',
    category: 'Asamyukta Hasta',
    meaning: 'Three Parts of a Flag',
    difficulty: 'Beginner',
    meaningLong: 'A variation of Pataka with the ring finger bent.',
    significance: 'Used for a crown, tree, or thunderbolt.',
    instructions: 'Form Pataka and bend the ring finger at the middle joint.',
    commonMistakes: 'Bending the other fingers along with the ring finger.',
    image: '/images/mudras/tripataka.jpg',
  },
  {
    id: '3',
    slug: 'ardhapataka',
    name: 'Ardhapataka',
    category: 'Asamyukta Hasta',
    meaning: 'Half Flag',
    difficulty: 'Intermediate',
    meaningLong: 'Like Tripataka but with the little finger also bent.',
    significance: 'Represents a knife, a bank of a river, or a saw.',
    instructions: 'From Tripataka, bend the little finger as well.',
    commonMistakes: 'Not keeping the index and middle fingers fully straight.',
    image: '/images/mudras/ardhapataka.jpg',
  },
  {
    id: '4',
    slug: 'kartarimukha',
    name: 'Kartarimukha',
    category: 'Asamyukta Hasta',
    meaning: 'Scissors Face',
    difficulty: 'Intermediate',
    meaningLong: 'Formed by crossing the index and middle fingers in a V-shape.',
    significance: 'Represents separation, lightning, or falling.',
    instructions: 'Bend the ring and pinky fingers to the palm. Extend index and middle fingers and spread them.',
    commonMistakes: 'Fingers not spread wide enough.',
    image: '/images/mudras/kartarimukha.jpg',
  },
  {
    id: '5',
    slug: 'mayura',
    name: 'Mayura',
    category: 'Asamyukta Hasta',
    meaning: 'Peacock',
    difficulty: 'Advanced',
    meaningLong: 'The tip of the thumb touches the tip of the ring finger.',
    significance: 'Represents a peacock, applying tilaka, or a creeper.',
    instructions: 'Touch ring finger tip to thumb tip. Keep other fingers spread and straight.',
    commonMistakes: 'Thumb not meeting the ring finger correctly.',
    image: '/images/mudras/mayura.jpg',
  },
  {
    id: '6',
    slug: 'arala',
    name: 'Arala',
    category: 'Asamyukta Hasta',
    meaning: 'Bent',
    difficulty: 'Intermediate',
    meaningLong: 'The index finger is bent like a hook.',
    significance: 'Represents drinking nectar or violent wind.',
    instructions: 'From Pataka, bend the index finger inwards while keeping others straight.',
    commonMistakes: 'Bending the middle finger along with the index.',
    image: '/images/mudras/arala.jpg',
  },
  {
    id: '7',
    slug: 'shukatunda',
    name: 'Shukatunda',
    category: 'Asamyukta Hasta',
    meaning: "Parrot's Beak",
    difficulty: 'Advanced',
    meaningLong: 'Like Arala but with the ring finger also bent.',
    significance: 'Represents a parrot’s beak or shooting an arrow.',
    instructions: 'From Arala, bend the ring finger as well.',
    commonMistakes: 'Losing the hook shape of the index finger.',
    image: '/images/mudras/shukatunda.jpg',
  },
  {
    id: '8',
    slug: 'alapadma',
    name: 'Alapadma',
    category: 'Asamyukta Hasta',
    meaning: 'Full-bloomed Lotus',
    difficulty: 'Beginner',
    meaningLong: 'All fingers are spread out and curved like a blooming flower.',
    significance: 'Represents a lotus, a mirror, or the full moon.',
    instructions: 'Separate and curve all fingers outwards starting from the pinky.',
    commonMistakes: 'Fingers being too straight or not enough rotation.',
    image: '/images/mudras/alapadma.jpg',
  },
  {
    id: '9',
    slug: 'ardhachandra',
    name: 'Ardhachandra',
    category: 'Asamyukta Hasta',
    meaning: 'Half Moon',
    difficulty: 'Beginner',
    meaningLong: 'Formed by stretching the thumb of the Pataka hand away from the fingers.',
    significance: 'Used to represent the moon, a spear, a platter, or catching someone by the throat.',
    instructions: 'From Pataka, stretch the thumb out as far as possible while keeping all other fingers tight and straight.',
    commonMistakes: 'Bending the index finger or thumb joints.',
    image: '/images/mudras/arthachandra.jpg',
  },
  {
    id: '10',
    slug: 'mushti',
    name: 'Mushti',
    category: 'Asamyukta Hasta',
    meaning: 'Closed Fist',
    difficulty: 'Beginner',
    meaningLong: 'A basic fist gesture where the thumb rests on the other four fingers.',
    significance: 'Used to represent fighting, strength, steadfastness, or grasping hair.',
    instructions: 'Curl all four fingers into the palm and fold the thumb over the middle and ring fingers.',
    commonMistakes: 'Tucking the thumb inside the fingers or leaving gaps in the fist.',
    image: '/images/mudras/mushti.jpg',
  },
  {
    id: '11',
    slug: 'shikhara',
    name: 'Shikhara',
    category: 'Asamyukta Hasta',
    meaning: 'Peak / Mountain Top',
    difficulty: 'Beginner',
    meaningLong: 'The thumb is raised from the Mushti gesture.',
    significance: 'Used for a bow, a pillar, a husband, silence, or a bell.',
    instructions: 'Form Mushti (fist) and then raise only the thumb straight up.',
    commonMistakes: 'Thumb not being fully vertical or fingers being too loose.',
    image: '/images/mudras/shikara.jpg',
  },
  {
    id: '12',
    slug: 'suchi',
    name: 'Suchi',
    category: 'Asamyukta Hasta',
    meaning: 'Needle',
    difficulty: 'Intermediate',
    meaningLong: 'The index finger is extended from a fist, resembling a needle.',
    significance: 'Used to represent the number one, the sun, a city, or pointing at something.',
    instructions: 'Form Mushti and extend only the index finger upwards.',
    commonMistakes: 'Bending the extended index finger or thumb sticking out.',
    image: '/images/mudras/suchi.jpg',
  },
  {
    id: '13',
    slug: 'chandrakala',
    name: 'Chandrakala',
    category: 'Asamyukta Hasta',
    meaning: 'Digit of the Moon',
    difficulty: 'Intermediate',
    meaningLong: 'Similar to Suchi but with the thumb also extended out.',
    significance: 'Represents the moon, the face, or the goddess Ganga.',
    instructions: 'Form Suchi and extend the thumb out at a right angle to the index finger.',
    commonMistakes: 'Thumb and index finger and not at a proper 90-degree angle.',
    image: '/images/mudras/chandrakala.jpg',
  },
  {
    id: '14',
    slug: 'padmakosha',
    name: 'Padmakosha',
    category: 'Asamyukta Hasta',
    meaning: 'Lotus Bud',
    difficulty: 'Intermediate',
    meaningLong: 'Fingers are curved like a bowl, resembling a budding lotus.',
    significance: 'Used for a fruit, a bud, a ball, or scattered flowers.',
    instructions: 'Stretch and curve all fingers including the thumb, keeping fingertips apart but close to each other.',
    commonMistakes: 'Fingers touching each other or being too straight.',
    image: '/images/mudras/padmakosha.jpg',
  },
  {
    id: '15',
    slug: 'sarpashirsha',
    name: 'Sarpashirsha',
    category: 'Asamyukta Hasta',
    meaning: "Snake's Head",
    difficulty: 'Intermediate',
    meaningLong: 'The palm is curved to resemble a cobra’s hood.',
    significance: 'Used for a snake, offering water, or a cradle.',
    instructions: 'From Pataka, hollow the palm slightly and curve the fingers forward like a hood.',
    commonMistakes: 'Bending the fingers too much or thumb sticking up.',
    image: '/images/mudras/sarpashirsha.jpg',
  },
  {
    id: '16',
    slug: 'simhamukha',
    name: 'Simhamukha',
    category: 'Asamyukta Hasta',
    meaning: 'Lion Face',
    difficulty: 'Advanced',
    meaningLong: 'The middle and ring fingers touch the thumb while others are extended.',
    significance: 'Represents a lion’s face, a rabbit, or a garland.',
    instructions: 'Extend index and little fingers. Touch middle and ring finger tips to the thumb tip.',
    commonMistakes: 'Thumb not touching BOTH middle and ring fingers.',
    image: '/images/mudras/simhamukha.jpg',
  },
  {
    id: '17',
    slug: 'mukula',
    name: 'Mukula',
    category: 'Asamyukta Hasta',
    meaning: 'Blossom / Bud',
    difficulty: 'Beginner',
    meaningLong: 'All five fingertips meet together to form a point.',
    significance: 'Used for a water lily, eating, or a small quantity.',
    instructions: 'Bring all five fingertips together so they touch each other at a single point.',
    commonMistakes: 'Thumb not meeting all four fingers at the tip.',
    image: '/images/mudras/mukula.jpg',
  },
  {
    id: '18',
    slug: 'trishula',
    name: 'Trishula',
    category: 'Asamyukta Hasta',
    meaning: 'Trident',
    difficulty: 'Advanced',
    meaningLong: 'Thumb and little finger are bent, while the three middle fingers are up.',
    significance: 'Used for the Trident (weapon of Shiva) or the number three.',
    instructions: 'Bend the thumb and pinky finger to the palm. Keep index, middle, and ring fingers straight.',
    commonMistakes: 'Bent fingers sticking out or top fingers overlapping.',
    image: '/images/mudras/trishula.jpg',
  },
  {
    id: '19',
    slug: 'anjali',
    name: 'Anjali',
    category: 'Samyukta Hasta',
    meaning: 'Salutation / Prayer',
    difficulty: 'Beginner',
    meaningLong: 'The most basic double-hand gesture, formed by joining two Pataka palms.',
    significance: 'Used for saluting God (above head), Guru (face level), or elders (chest level).',
    instructions: 'Simply join the palms of both hands together in a prayer position.',
    commonMistakes: 'Gaps between fingers or palms not touching completely.',
    image: '/images/mudras/anjali.jpg',
  },
  {
    id: '20',
    slug: 'kapota',
    name: 'Kapota',
    category: 'Samyukta Hasta',
    meaning: 'Pigeon',
    difficulty: 'Intermediate',
    meaningLong: 'A variation of Anjali where the palms are hollowed.',
    significance: 'Represents a pigeon, taking an oath, or humble acceptance.',
    instructions: 'From Anjali, touch only the tips and sides of the fingers and palms, hollowing the center.',
    commonMistakes: 'Fingers being too stiff or palms touching at the center.',
    image: '/images/mudras/kapota.jpg',
  },
  {
    id: '21',
    slug: 'karkata',
    name: 'Karkata',
    category: 'Samyukta Hasta',
    meaning: 'Crab',
    difficulty: 'Intermediate',
    meaningLong: 'Fingers of both hands are interlocked.',
    significance: 'Used for a group of people, stretching the body, or blowing a conch.',
    instructions: 'Interlock the fingers of both hands together, either facing inwards or outwards.',
    commonMistakes: 'Loose interlocking or incorrect palm orientation.',
    image: '/images/mudras/karkata.jpg',
  },
  {
    id: '22',
    slug: 'swastika-double',
    name: 'Swastika',
    category: 'Samyukta Hasta',
    meaning: 'Crossed',
    difficulty: 'Beginner',
    meaningLong: 'Two Pataka hands crossed at the wrists.',
    significance: 'Represents a crocodile, an argument, or saying "No".',
    instructions: 'Cross both hands at the wrists with palms facing sideways or towards each other.',
    commonMistakes: 'Crossing at the forearms instead of the wrists.',
    image: '/images/mudras/swastika.jpg',
  },
  {
    id: '23',
    slug: 'shivalinga',
    name: 'Shivalinga',
    category: 'Samyukta Hasta',
    meaning: 'Sign of Shiva',
    difficulty: 'Intermediate',
    meaningLong: 'A combination of Shikhara on the right and Pataka on the left.',
    significance: 'Specifically used to represent Lord Shiva or the Linga.',
    instructions: 'Hold Shikhara (fist with thumb up) in the right hand and place it on the left Pataka palm.',
    commonMistakes: 'Incorrect hand placement or Shikhara not being centered.',
    image: '/images/mudras/shivalinga.jpg',
  },
  {
    id: '24',
    slug: 'pushpaputa',
    name: 'Pushpaputa',
    category: 'Samyukta Hasta',
    meaning: 'Flower Casket',
    difficulty: 'Intermediate',
    meaningLong: 'Two Sarpashirsha hands joined at the sides.',
    significance: 'Used for offering flowers, receiving gifts, or drinking water.',
    instructions: 'Join both Sarpashirsha (snake head) hands together by the little finger sides to form a bowl.',
    commonMistakes: 'Gaps between the hands or losing the curve of the palms.',
    image: '/images/mudras/pushpaputa.jpg',
  },
  {
    id: '25',
    slug: 'shankha',
    name: 'Shankha',
    category: 'Samyukta Hasta',
    meaning: 'Conch Shell',
    difficulty: 'Advanced',
    meaningLong: 'A complex interlocking of hands to represent a shell.',
    significance: 'Represents the holy conch shell used in rituals.',
    instructions: 'Wrap the left four fingers around the right thumb; touch the right fingers to the left thumb.',
    commonMistakes: 'Thumb positioning being wrong or the "shell" shape being unclear.',
    image: '/images/mudras/shankha.jpg',
  },
  {
    id: '26',
    slug: 'chakra-double',
    name: 'Chakra',
    category: 'Samyukta Hasta',
    meaning: 'Discus / Wheel',
    difficulty: 'Intermediate',
    meaningLong: 'Two Ardhachandra hands placed against each other.',
    significance: 'Specifically represents the Sudarshana Chakra of Lord Vishnu.',
    instructions: 'Place the palms of two Ardhachandra hands against each other at a right angle.',
    commonMistakes: 'Incorrect angle between the two palms.',
    image: '/images/mudras/chakra.jpg',
  },
  {
    id: '27',
    slug: 'matsya',
    name: 'Matsya',
    category: 'Samyukta Hasta',
    meaning: 'Fish',
    difficulty: 'Beginner',
    meaningLong: 'One hand placed on top of the other with thumbs out.',
    significance: 'Represents a fish or the Matsya Avatar (Fish incarnation).',
    instructions: 'Place one Pataka palm on the back of the other, with both thumbs extended like fins.',
    commonMistakes: 'Thumbs not being stretched out or palms not being flat on each other.',
    image: '/images/mudras/matsya.jpg',
  },
  {
    id: '28',
    slug: 'garuda',
    name: 'Garuda',
    category: 'Samyukta Hasta',
    meaning: 'Eagle / Bird',
    difficulty: 'Beginner',
    meaningLong: 'Thumbs interlocked with fingers spread like wings.',
    significance: 'Points to the mythical bird Garuda or any large bird taking flight.',
    instructions: 'Interlock the thumbs and spread all other fingers wide while moving the hands.',
    commonMistakes: 'Thumbs coming apart or fingers being too close together.',
    image: '/images/mudras/garuda.jpg',
  },
];
